version: '3.7'

services:
  mongo:
    image: mongo:5.0.1
    container_name: mo-mongo
    ports:
      - 28017:27017
    volumes:
      - mongo_db:/data/db
      - mongo_configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mo-mongo-express
    ports:
      - 8881:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    restart: unless-stopped
    depends_on:
      - mongo

  couchbase:
    image: couchbase:enterprise-7.0.1
    container_name: mo-couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    volumes:
      - couchbase_var:/opt/couchbase/var
      - ./scripts:/scripts
    restart: unless-stopped

volumes:
    mongo_db:
        # external: true // Specify if you wish to create yourself
    mongo_configdb:
        # external: true // Specify if you wish to create yourself
    couchbase_var: